name: preprod-tests

on:
  pull_request:
    branches: [ production ]
    types: [ opened, synchronize, reopened ]

jobs:
  tests:
    if: github.event.pull_request.base.ref == 'production' && github.event.pull_request.head.ref == 'master'
    runs-on: ubuntu-latest
    name: tests
    permissions:
      contents: read
    steps:
      - name: Checkout PR merge ref
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.3
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-py3.13-poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies (with dev)
        run: poetry install --with dev --no-interaction

      - name: Run tests
        run: poetry run pytest -q
