name: preprod-tests  # <= важно: совпадает с тем, что вы выбрали в required

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        default: '3.13'

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    timeout-minutes: 25
    permissions:
      contents: read
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs['python-version'] }}
          cache: 'pip'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.3
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-py${{ inputs['python-version'] }}-poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies (with dev)
        run: poetry install --with dev --no-interaction

      - name: Run tests
        run: poetry run pytest -q
